DROP TABLE IF EXISTS nicd;
CREATE TABLE nicd(
   FirstName       TEXT ,
  LastName        TEXT NOT NULL,
  PersonID        INTEGER ,
  Email           TEXT,
  Programme       TEXT,
  School          TEXT,
  delivery_method TEXt,
  GroupID         INTEGER,
  VMID            TEXT(14) NOT NULL
);
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Thomas','Tilley',190642145,'t.tilley1@newcastle.ac.uk','Mechanical Engineering MEng','School of Engineering','Remote',10,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Katie','Teale',190222442,'k.teale1@newcastle.ac.uk','Mathematics','School of Mathematics, Statistics and Physics','Remote',10,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Jakub','Roks',190398851,'j.d.roks1@newcastle.ac.uk','BSc Computer Science','School of Computing','Remote',10,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Bartosz','Borowski',190405399,'b.borowski1@newcastle.ac.uk','Combined Honours',NULL,'Remote',10,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Abdul','Hawisa',190026208,'a.hawisa1@newcastle.ac.uk','Electronic and Computer Engineering','School of Engineering','Remote',10,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Vikram','Sengupta',190641344,'v.r.sengupta2@newcastle.ac.uk','Electrical and Electronic Engineering BEng (Hons)','School of Engineering','Campus',1,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Shannon','Quinn',180020760,'s.quinn1@newcastle.ac.uk','Mathematics and Psychology','School of Mathematics, Statistics and Physics','Campus',1,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Hasab','Osman',90604774,'h.a.a.a.osman1@newcastle.ac.uk','BSc Statistics','School of Mathematics, Statistics and Physics','Campus',1,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Harsev','Singh',180034918,'h.singh5@newcastle.ac.uk','Mechanical Engineering','School of Engineering','Campus',1,'databootcamp-1');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Mateo','Ribadeneira',190652100,'m.s.ribadeneira-naranjo2@newcastle.ac.uk','Civil engineering','School of Engineering','Remote',9,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Matthew','Cresswell',190319650,'m.cresswell2@newcastle.ac.uk','Single Honours Mathematics','School of Mathematics, Statistics and Physics','Remote',9,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Grace','Kilday',190185778,'g.kilday1@newcastle.ac.uk','Chemistry with Medicinal Chemistry','School of Natural and Environmental Sciences','Remote',9,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Shah Murad','Bajwa',190645191,'s.m.bajwa2@newcastle.ac.uk','Chemical Engineering','School of Engineering','Remote',9,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Natalie','Mackworth-Praed',190105374,'n.e.mackworth-praed1@newcastle.ac.uk','Mechanical Engineering with Biomedical Engineering','School of Engineering','Campus',2,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Krittima','Thuphom',180651863,'k.thuphom2@newcastle.ac.uk','Beng civil and structural engineering','School of Engineering','Campus',2,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('MARCO','WAN',200029663,'y.h.wan2@newcastle.ac.uk','Statistical Method for Marketing and Management','School of Mathematics, Statistics and Physics','Campus',2,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Mirkena','Hundessa',150650555,'m.a.hundessa1@newcastle.ac.uk','Geographic Information Science','School of Engineering','Campus',2,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Syed','Haque',190175964,'s.wasiful-haque1@newcastle.ac.uk','BSc Mathematics','School of Mathematics, Statistics and Physics','Campus',2,'databootcamp-2');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Aaron','Slight',190272654,'a.c.slight1@newcastle.ac.uk','Mechanical Engineering','School of Engineering','Remote',8,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Debarghyo','Pandit',190643522,'d.pandit1@newcastle.ac.uk','Mechanical Engineering','School of Engineering','Remote',8,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Linda','Amponsah',190446510,'l.amponsah1@newcastle.ac.uk','Chemistry','School of Natural and Environmental Sciences','Remote',8,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Adam','Gough',190296694,'a.gough1@newcastle.ac.uk','Mathematics','School of Mathematics, Statistics and Physics','Remote',8,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('James','McKelvey',190300681,'j.r.mckelvey1@newcastle.ac.uk','Geographic Information Systems','School of Engineering','Campus',3,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Mohammed','Ali',180310096,'m.ali19@newcastle.ac.uk','Electronics and Computer Engineering','School of Engineering','Campus',3,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Simran','Aujla',180705454,'s.aujla1@newcastle.ac.uk','Mathematics','School of Mathematics, Statistics and Physics','Campus',3,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Rebecca','Watts',180362970,'r.watts@newcastle.ac.uk','Earth Science','School of Natural and Environmental Sciences','Campus',3,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('David','Byers',190236461,'d.byers1@newcastle.ac.uk','Electrical and Electronic Engineering','School of Engineering','Campus',3,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Natan','Sopterean',190643670,'n.sopterean1@newcastle.ac.uk','Eloctronics and Computer Engineering','School of Engineering','Remote',7,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Paulina','Barteskaite',190385448,'p.barteskaite1@newcastle.ac.uk','BEng Civil and Structural engineering','School of Engineering','Remote',7,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Greg','Knight',190638849,'g.c.e.knight1@newcastle.ac.uk','Biology','School of Natural and Environmental Sciences','Remote',7,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Peter','Lennard-Jones',190625539,'p.lennard-jones1@newcastle.ac.uk','Mathematics','School of Mathematics, Statistics and Physics','Remote',7,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Nathan','Smith',190169332,'n.smith11@newcastle.ac.uk','Marine Technology','School of Engineering','Campus',4,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('James','Shanks',9018378,'j.m.a.shanks1@newcastle.ac.uk','Mechanical Engineering','School of Engineering','Campus',4,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Oliver','Carey',200648730,'o.n.de-vic-carey2@newcastle.ac.uk','Mathematics and Statistics','School of Mathematics, Statistics and Physics','Campus',4,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Caitlin','Storry',9010850,'c.storry@newcastle.ac.uk','Chemistry','School of Natural and Environmental Sciences','Campus',4,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Javed Nahim','Islam',190394990,'j.n.islam1@newcastle.ac.uk','Bsc Hons Mathematics and Economics','School of Mathematics, Statistics and Physics','Campus',4,'databootcamp-4');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Salman','Alawadhi',180650110,'s.i.i.e.alawadhi2@newcastle.ac.uk','Chemical engineering','School of Engineering','Remote',6,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Reuben','Atherton',19032315,'r.atherton2@newcastle.ac.uk','Electrical and Electronic Engineering','School of Engineering','Remote',6,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Nektarios Aristeidis','Tafanidis',190420989,'n.a.tafanidis1@newcastle.ac.uk','H607 - Beng Hons Electrical and Electronic Engineering','School of Engineering','Remote',6,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Polina','Lytvyn',180651184,'p.lytvyn2@newcastle.ac.uk','Computer Science','School of Computing','Remote',6,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Kevin','Jashari',190394794,'k.jashari1@newcastle.ac.uk','Mechanical Engineering Beng','School of Engineering','Remote',6,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Shiva','Sharma',190637130,'s.sharma8@newcastle.ac.uk','electrical and electronics engineering','School of Engineering','Campus',5,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Holly','Park',190062907,'h.park5@newcastle.ac.uk','MMATH','School of Mathematics, Statistics and Physics','Campus',5,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Benjamin','Morrow',180717538,'b.morrow2@newcastle.ac.uk','Mathematics','School of Mathematics, Statistics and Physics','Campus',5,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Bashir','Ayvazian',190286709,'b.ayvazian-kassis2@newcastle.ac.uk','Civil and Structural Engineering','School of Engineering','Campus',5,'databootcamp-5');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Jordan','Ellwood',NULL,NULL,NULL,NULL,NULL,NULL,'databootcamp-3');
INSERT INTO nicd(FirstName,LastName,PersonID,Email,Programme,School,delivery_method,GroupID,VMID) VALUES ('Anna','Marczynska',NULL,NULL,NULL,NULL,NULL,NULL,'databootcamp-3');
